(function LoremIpsum() {

    var gamerIpsums = [
        'game',
        'RPG',
        'Rock Paper Shotgun',
        'Steam',
        'LOL',
        'hashtag',
        'journalism',
        'corruption',
        'video games',
        'Twitter',
        'Unity',
        'development',
        'developer',
        'developing',
        'studio',
        'mobile',
        'mobile phone',
        'HTML5',
        'free to play',
        'Jonathan Blow',
        'YouTube',
        'Let’s Play',
        'Twitch',
        'stream',
        'streaming',
        'magazine',
        'blog',
        'coding',
        'code',
        'WASD',
        'publishing',
        'selling',
        'racing',
        'adventure',
        'action',
        'point and click',
        'PC Gaming Master Race',
        'genre',
        'new',
        'HD',
        'internet',
        'download',
        'sequel',
        'fans',
        'love',
        'hate',
        'Oculus Rift',
        'local multiplayer',
        'share',
        'keyboard',
        'mouse',
        'gamepad',
        'display',
        'television',
        'bundle',
        'portable',
        'award',
        '10/10',
        'iPhone',
        'iPad',
        'iOS',
        'simulation',
        'sex',
        'patch',
        'puzzle',
        'crack',
        'Flash',
        'remake',
        'level design',
        'cheat code',
        'hype',
        'port',
        'Adblock',
        'beta',
        'GOTY',
        'OMG',
        'crap',
        'arcade',
        'arcade machine',
        'pinball',
        'beat ‘em up',
        'Mac',
        'Linux',
        'emotions',
        'preview',
        'demo',
        'Polygon',
        'Kotaku',
        'smartphone',
        'open world',
        'music',
        'soundtrack',
        'theme',
        'vlog',
        'Errant Signal',
        'rip-off',
        'digital',
        'FTW',
        'John D. Carmack',
        'shitstorm',
        'Edge',
        'split-screen',
        'game over',
        'walkthrough',
        'playthrough',
        'teamchat',
        '1up',
        'extra life',
        'co-op',
        'closed beta',
        'public beta',
        'speedrun',
        'sports',
        'soccer',
        'community',
        'communities',
        'canceled',
        'magazine',
        'crafting',
        'multiplayer',
        'server',
        'shard',
        'Game Boy',
        'table top',
        'sci-fi',
        'fantasy',
        '3D',
        'horror',
        'survial horror',
        'shooter',
        'shmup',
        'real-time',
        'tactical',
        'serious gaming',
        'quiz',
        'strategy',
        'underwater level',
        'level editor',
        'basketball',
        'hockey',
        'Pong',
        'GDC',
        'virtual',
        'VR',
        'golf',
        'tennis',
        'wrestling',
        'fun',
        'character editor',
        'tank',
        'A.I.',
        'loot',
        'desktop',
        'top-down',
        'visceral',
        'internet',
        'browser game',
        'sexism',
        'nudism',
        'violence',
        'mana',
        'items',
        'noob',
        'energy',
        'god mode',
        'inventory',
        'interface',
        'armor',
        'lightsword',
        'lightgun',
        'manager',
        'Atari 2600',
        'SNES',
        'NES',
        'cartridge',
        'god game',
        'torture',
        'Android',
        'extra life',
        'killed',
        'space ship',
        'railgun',
        'system requirements',
        'easter egg',
        'mod',
        'modding',
        'texture',
        'anti-aliasing',
        'sale',
        'polish',
        'drama',
        'trailer',
        'teaser',
        'video',
        'easy',
        'hard',
        'medium',
        'nightmare',
        'difficulty',
        'social',
        'social network',
        'connected',
        'update',
        'Steam Curation',
        'browser based',
        'games',
        'gaming',
        'streamlined',
        'gamer',
        'spiritual',
        'Dota',
        'Defense of the Ancients',
        'Dota 2',
        'GOG',
        'Appstore',
        'Google Play',
        'Tim Schafer',
        'forum',
        'member',
        'team',
        'online',
        'offline',
        'reboot',
        'Linux',
        'Windows',
        'Mac OS X',
        'PC',
        'OS',
        'operating system',
        'year of the Linux desktop',
        'future',
        'science fiction',
        'car',
        'rogue',
        'something',
        'support',
        'announces',
        'announcement',
        'website',
        'homepage',
        'realm',
        'local',
        'digital distribution',
        'history',
        'gameplay',
        'Software Development Kit',
        'Kill Screen',
        'Joystiq',
        '2014',
        '2015',
        '2016',
        'press coverage',
        'SDK',
        'chess',
        're-release',
        'JRPG',
        'Anita Sarkeesian',
        'stealth',
        'Double Fine',
        'Ron Gilbert',
        'Steam Machine',
        'Big Picture',
        '2560x1440',
        'achievements',
        'summer sale',
        'artist',
        'Game Developers Conference',
        'Chris Crawford',
        'Abandonware',
        'depth',
        'damsel in distress',
        'princess',
        'dragon',
        'writer',
        'map editor',
        'level design',
        'literature',
        'kids',
        'children',
        'family',
        'teenager',
        'adults',
        'customer',
        'clients',
        'client',
        'porn',
        'downsampling',
        'supersampling',
        'random',
        'random generator',
        'randomized',
        'alpha',
        'pre-alpha',
        'open beta',
        'closed beta',
        'invite',
        'drag and drop',
        'press',
        'journalists',
        'interview',
        'article',
        'text',
        'podcast',
        'device',
        'devices',
        'electronic',
        'speed',
        'famous',
        'infamous',
        'war',
        'combat',
        'conflict',
        'enemy',
        'enemies',
        'party',
        'select',
        'start',
        'challenging',
        'investment',
        'learning',
        'easy to learn',
        'hard to master',
        'bug',
        'bugged',
        'feature',
        'featured',
        'broken'
    ];

    var indieIpsums = [
        '8-Bit',
        '16-Bit',
        'pixel',
        'Humble Bundle',
        'Zoe Quinn',
        'Depression Quest',
        'IGF',
        'Ludum Dare',
        'Gamejam',
        'cactus',
        'chiptunes',
        'free',
        'minimalist',
        'retro',
        'provocative',
        'inclusive',
        'festival',
        'A MAZE',
        'indie',
        'independent',
        'small',
        'smaller',
        'focussed',
        'twine',
        'thoughtful',
        'Kickstarter',
        'style',
        'art',
        'Greenlight',
        'Desura',
        'early access',
        'students',
        'itch.io',
        'idea',
        'project',
        'unfinished',
        'concept',
        'prototype',
        'FEZ',
        'Super Meat Boy',
        'Spelunky',
        'game studies',
        'Team Meat',
        'indiegames.com',
        'C64',
        'emulation',
        'platformer',
        'Phil Fish',
        'freeware',
        'Kentucky Route Zero',
        'Superlevel',
        'walking simulator',
        'Anna Anthropy',
        'Hotline Miami',
        'Braid',
        'Antichamber',
        'Nidhogg',
        'Vlambeer',
        'Luftrausers',
        'Johann Sebastian Joust',
        'demake',
        'glitch',
        'Goat Simulator',
        'TIGSource',
        'tumblr',
        'devlog',
        'open source',
        '2D Boy',
        'World of Goo',
        'Amanita Design',
        'Broken Rules',
        'Super Time Force',
        'Superbrothers: Sword & Sworcery EP',
        'Christine Love',
        'Digital: A Love Story',
        'Dear Esther',
        'Amnesia: A Machine for Pigs',
        'Analogue: A Hate Story',
        'The Chinese Room',
        'Daniel Benmergui',
        'Dennaton Games',
        'Derek Yu',
        'Edmund McMillen',
        'The Binding of Isaac',
        'Erik Svedäng',
        'Garry\'s Mod',
        'Gaijin Games',
        'Bit.Trip Runner',
        'Flappy Bird',
        'Jason Rohrer',
        'Passage',
        'Jonas Kyratzes',
        'Jonatan "Cactus" Söderström',
        'Don\'t Starve',
        'Kloonigames',
        'Messhof',
        'Molleindustria',
        'Cave Story',
        'Nifflas',
        'Knytt Stories',
        'Limbo',
        'Terraria',
        'Bastion',
        'Tale of Tales',
        'text adventure',
        'artsy',
        'funding',
        'windowed',
        'test build',
        'Rasberry Pi',
        'exploring',
        'explore',
        'endless runner',
        'Canabalt',
        'Adam Atomic',
        'atmosphere',
        'depression',
        'unlimited',
        'love',
        'Sweden',
        'exploration',
        'art style',
        'color palette',
        'respect',
        'Pippin Barr',
        'greenlit',
        'interactive fiction',
        '2D',
        'jump’n’run',
        'voxel',
        'PAX',
        'conference',
        'Indie Game: The Movie',
        'gamification',
        '80s',
        'parallax scrolling',
        'McPixel',
        'tollerance',
        'Indiegogo',
        'pretentious',
        'low-poly',
        '1-Bit',
        'charming',
        'low budget',
        'clones',
        'self-publishing',
        'trash',
        'lovely',
        'peaceful',
        'happy',
        'Castle Crashers',
        'passion',
        'Terry Cavanagh',
        'Lucas Pope',
        'VVVVVV',
        'Indie Mega Booth',
        'procedural content generation',
        'procedual',
        'niche market',
        'rogue-like',
        'permadeath',
        'FTL',
        'quirky',
        'small team',
        'individuals',
        'no budget',
        'independent',
        'individual involvement',
        'innovation',
        'creativity',
        'artistic',
        'experimentation',
        'crowdfunding',
        'Crayon Physics Deluxe',
        'Legend of Grimrock',
        'Samorost',
        'Crypt of the Necrodancer',
        'Gone Home',
        'Prison Architect',
        'Polytron Corporation',
        'Desktop Dungeons',
        'The Banner Saga',
        'IndieDB',
        'Gnome’s Lair',
        'Game Jolt',
        'IndieCade',
        'SourceForge',
        'rpgmaker',
        'PixelProspector',
        'Humble Store',
        'SUPER HOT',
        'vintage',
        'neo-retro',
        'not-game',
        'visual novel',
        'adult',
        'DIY',
        'Eggplant run',
        '320x240',
        'Indie Fund',
        'Penny Arcade',
        'pixelated',
        'blocky',
        'deep',
        'limitations',
        'non-profit',
        'hobbyist',
        'non-commercial',
        'scene',
        'open',
        'rise',
        'inspiration',
        'inspired',
        'movement',
        'shareware',
        'risk',
        'risky',
        'small-size',
        'funding',
        'vision',
        'dream',
        'sprites',
        'tiles',
        'failure',
        'success'
    ];

    var AAAIpsum = [
        'Electronic Arts',
        'Ubisoft',
        'Nintendo',
        'Miyamoto',
        'Sony',
        'PlayStation 4',
        'PlayStation 3',
        'Microsoft',
        'Minecraft',
        'Mojang',
        '@notch',
        'FIFA',
        'Call of Duty',
        'Zynga',
        'Mario',
        'Zelda',
        'Farmville',
        'money',
        'Mountain Dew',
        'Doritos',
        'revolutionary',
        'shader',
        'incredible',
        'amazing',
        'technology',
        'exclusive',
        'DLC',
        'polygons',
        'Apple',
        'console',
        'next-generation',
        'pre-order',
        'explosions',
        'weapons',
        'MMO',
        'experience',
        'gamescom',
        'AAA',
        'era',
        'redefine',
        'Facebook',
        'IAP',
        'graphics card',
        'FPS',
        'licensed',
        'IP',
        'new IP',
        'Battlefield',
        'Blizzard',
        'Diablo',
        'StarCraft',
        'World of Warcraft',
        'Warcraft',
        'Hearthstone',
        'Bigpoint',
        'Nanomachines',
        'Madden',
        'NFL',
        'Konami',
        'Capcom',
        'Warner Bros. Interactive',
        'Paradox Interactive',
        '505 Games',
        'Atlus',
        'Tecmo',
        'Deep Silver',
        'Focus Home Interactive',
        'Kalypso Media',
        'Rockstar',
        'GTA',
        'Metacritic',
        'Bioshock',
        'engine',
        'warez',
        'torrent',
        'rapidshare',
        'Dark Souls',
        'Sims',
        'Final Fantasy',
        'region lock',
        'Wii',
        'Wii U',
        'Vita',
        'reboot',
        'preload',
        'Sega',
        'Sonic',
        'flight simulator',
        'collector’s edition',
        'dvd',
        'Blu-ray',
        'nude patch',
        'Season Pass',
        'DRM',
        '1080p',
        '60 FPS',
        'On-Disc',
        '100%',
        'vaporware',
        'Daedalic',
        'Gronkh',
        'impressive',
        'PewDiePie',
        'policy',
        'Counter-Strike',
        'AD&D',
        'farming',
        'eSports',
        'Will Wright',
        'Richard Garriott',
        'David Braben',
        'Gabe Newell',
        'Al Lowe',
        'Markus Persson',
        'John Romero',
        'Sid Meier',
        'Hideo Kojima',
        'Metal Gear',
        'Ken Levine',
        'Jade Raymond',
        'Assassin\'s Creed',
        'Hironobu Sakaguchi',
        'Warren Spector',
        'Thief',
        'Deus Ex',
        'Star Trek',
        'Atari',
        'HDMI',
        'Donkey Kong',
        '4K',
        'Star Wars',
        'Hans Zimmer',
        'Peter Molyneux',
        'Peter Moore',
        'Pokémon',
        'Doom',
        'Quake',
        'Wolfenstein',
        '16:9',
        'dolby digital',
        'add-on',
        'Macbook',
        'always online',
        'sold',
        'business',
        'Amazon',
        'Google',
        'sellout',
        'contract',
        'bizz',
        'PR',
        'agency',
        'subscription',
        'Dollar',
        'cash',
        '$$$',
        '1 Million',
        '1 Billion',
        'EA',
        'free-to-play',
        'F2P',
        'Dungeon Keeper',
        'Simpsons',
        'Square Enix',
        'MMORPG',
        'monetize',
        'Lara Croft',
        'Tomb Raider',
        'limited',
        'marketing',
        'market',
        'extra-ordinary',
        'photo realism',
        'FPS',
        'Need for Speed',
        'Third-Person-Shooter',
        'WWE',
        'World War I',
        'World War II',
        'Tamagotchi',
        'Street Fighter',
        'F1',
        'capital',
        'capitalism',
        'Wario',
        'tycoon',
        'retina',
        'Xbox One',
        'Xbox 360',
        'football manager',
        'Win8',
        'Gotham',
        'Batman',
        'Director’s Cut',
        'Premium Edition',
        'frames per second',
        'AMD',
        'Nvidia',
        'i5',
        'i7',
        '16GB RAM',
        'DDR',
        '8 Cores',
        'VRAM',
        'the cloud',
        'Geforce',
        'drivers',
        'cinematic',
        'micro-transactions',
        'franchise',
        'acclaimed',
        'PES',
        'epic',
        'in-game advertising',
        'Drivatar',
        'Levolution',
        'realistic',
        'innovative',
        'Duke Nukem',
        'Guybrush Threepwood',
        'Monkey Island',
        'DOS',
        'PSN',
        'Nintendo eShop',
        'Xbox Live Arcade',
        'day-one',
        'Larry Laffer',
        'Roger Wilco',
        'Gabriel Knight',
        'Andrew Ryan',
        'DirectX 11',
        'MOBA',
        'Far Cry 2',
        'Intel(R)',
        'expensive',
        'buzzword',
        'Konami code',
        '↑↑↓↓←→←→BA',
        'financial',
        'mainstream',
        'big budget',
        'creative limitations',
        'profit',
        'prominent',
        'industry',
        'high quality',
        'motion capturing',
        'high end graphics',
        'Unreal',
        'LOTR',
        'Marvel',
        'Superman',
        'Halo',
        'Mario Kart',
        'Game Center',
        'GameStop',
        'SWTOR',
        'water reflection',
        'copyright',
        'trademark',
        'Crytek',
        'Activision',
        'E.T.',
        'New Mexico landfill',
        'PEGI 18+',
        'pay-to-win',
        'Grand Theft Auto',
        'boobs physics',
        'male protagonist',
        'orchestral',
        'gamestar.de',
        'OSX',
        'Candy Crush',
        'king.com',
        'Pac-Man',
        'FXAA',
        '16x',
        'iPhone 6 Plus',
        'shading',
        'HDR',
        'DualShock',
        'Ultima',
        'trading cards',
        'three-headed monkey',
        'life-changing',
        'stock'
    ];

    var conjunction = [
        'and',
        'or',
        'but',
        'not',
        'because',
        'even if',
        'if',
        'when',
        'while',
        'although',
        'since',
        'otherwise',
        'was',
        'and',
        'it\'s like',
        'so',
        'before',
        'nor',
        'until',
        'despite',
        'for',
        'in',
        'by',
        'and',
        'of',
        '&'
    ];

    var quotes = [
        'Do a barrel roll!',
        'All your base are belong to us.',
        'The Kid just rages for a while.',
        'Big...money! Big...prizes! I love it!',
        'Henshin a go-go, baby!',
        'The Train’s at home on the rails!',
        'Fus-ro-dah!',
        'Say, fuzzy pickles.',
        'Welcome to Summoner’s Rift.',
        'It’s super effective!',
        'Jason! Jaaaaaaaaason!',
        'Save me!',
        'Job\'s done.',
        'I need shoes!',
        'Show me your moves!',
        'REVIVE ME!',
        'Good thinking, little buddy.',
        'Every puzzle has an answer.',
        'It’s dangerous to go alone; take this!',
        'I am error.',
        'Hey! Listen!',
        'Frankly, I’m ashamed.',
        'A nosy old hag like you knows everything about the people who live under her roof. Where did she go?',
        'It is pitch black. You are likely to be eaten by a grue.',
        'It\'s time to kick ass and chew bubble gum, and I\'m all out of gum.',
        'Requiescat in pace.',
        'Wait, that’s not how it happened.',
        'Objection!',
        'Leon!',
        'Wakka wakka wakka!',
        'Wyonk wyonk wyonk… wyonk wyonk.',
        'AREEEEEEEEEES!!!!!!!!!',
        'It’s TIME TO SPLIT!',
        'I’ve covered wars, you know.',
        'You were almost a Jill sandwich!',
        'I need a weapon.',
        'Wake me when you need me.',
        'Why not take a break? You can pause the game by pressing +.',
        'You spoony bard!',
        'Sonic Boom!',
        'Segaaaaaaaaaaaaaaaaaaaaa.',
        'Hadouken!',
        'Shoryuken!',
        'EA Sports! It’s in the game.',
        'Oh! My car!',
        'Spy\'s sappin\' my sentry!',
        'Reticulating splines.',
        'The President has been kidnapped by ninjas. Are you a bad enough dude to rescue the president?',
        'Big American titties!',
        'Hey dudes thanks, for rescuing me. Let\'s go for a burger....Ha! Ha! Ha! Ha!',
        'Welcome to your doom!',
        'Is a man not entitled to the sweat of his brow?',
        'A man chooses; a slave obeys.',
        'I feel asleep!!',
        'Snake? Snake? SNAAAAAAAAKE!!!',
        'War has changed.',
        'War. War never changes.',
        'Nuclear launch detected.',
        'You must construct additional pylons.',
        'In the year 200x a super robot named Mega Man was created.',
        'They call me Gato, I have metal joints. Beat me up and win 15 Silver Points.',
        'C-c-c-combo breaker!',
        'You can\'t break a man the way you do a dog or a horse - the harder you beat a man, the taller he stands.',
        'Killtacular!',
        'What is a man? A miserable little pile of secrets.',
        'M-M-M-M-MONSTER KILL!',
        'Boomshakalaka!',
        'Finish him!!',
        'Toasty!',
        'Get over here!',
        'Stay frosty.',
        'Oh look, another visitor. Stay awhile... Stay FOREVER!',
        'Hey hey hey it\'s time to make some carrrrazzzyy money!',
        'Stay a while, and listen!',
        'Thank you Mario! But our Princess is in another castle!',
        'You have died of dysentery.',
        'Blue Wizard is about to die.',
        'X-Men, welcome to die!',
        'YOU AND YOUR FRIENDS ARE DEAD.',
        'Congratulation. This story is happy end. Thank you.',
        'Conglaturation! You have completed a great game!',
        'A winner is you!',
        'Suffer, like G did.',
        'Motherf***er!',
        'I will kill your dicks!',
        'This is your fault. I\'m going to kill you. And all the cake is gone. You don\'t even care, do you?',
        'Everything is teetering on the edge of everything.',
        'The right man in the wrong place can make all the difference in the world.',
        'First blood!',
        'I am the great mighty poo, and I’m going to throw my shit at you.'
    ];

    function GaemzIpsum(neutralRatio, conjunctionRate) {
        this.neutralRatio = neutralRatio || 0.5;
        this.conjunctionRatio = conjunctionRate || 0.3;
        this.lastSentenceHadQuote = false;
        this.lastSentenceHadComma = false;
    }

    function getRandomWordByCategory(category, previous) {
        // Check for duplicates
        var word;
        do {
            word = getRandomInt(0, category.length-1);
        } while (category[word] === previous);

        return category[word];
    }

    GaemzIpsum.prototype.createSentence = function(length, indieRatio, comma) {
        length = length || 7;
        indieRatio = indieRatio || 0;
        comma = comma || false;

        var sentenceParts = [],
            sentence,
            indieToAAARatio,
            previous = null,
            word = '',
            randomRatio,
            conjunctionOccurrence = Math.random(),
            sentenceLength = length,
            wasConjunction,
            quoteRatio = Math.random();

        while (length--) {

            // Prevent same words follow up.
            randomRatio = Math.random();

            if (randomRatio > this.neutralRatio) {
                indieToAAARatio = Math.random();

                word = (indieRatio > 0 && indieToAAARatio < indieRatio)
                        ? getRandomWordByCategory(indieIpsums, previous)
                        : getRandomWordByCategory(AAAIpsum, previous);

            } else {
                // Normal
                wasConjunction = (conjunction.indexOf(previous) > -1);

                if (!wasConjunction &&
                    length > 1 &&
                    length < sentenceLength - 1  &&
                    conjunctionOccurrence < this.conjunctionRatio
                ) {
                    word = getRandomWordByCategory(conjunction, previous);
                } else {
                    word = getRandomWordByCategory(gamerIpsums, previous);
                }
            }

            previous = word;
            sentenceParts.push(word);
        }

        sentence = sentenceParts.join(' ');

        // add a quote?
        if (!this.lastSentenceHadQuote && quoteRatio < 0.5 && quoteRatio > indieRatio) {
            sentence += ": " + quotes[getRandomInt(0, quotes.length - 1)];
            this.lastSentenceHadQuote = true;
        } else {
            // check if we should use a comma
            if (!this.lastSentenceHadComma && comma && Math.random() < 0.1) {
                sentence += ',';
                this.lastSentenceHadComma = true;
            }
            else {
                sentence += Math.random() < 0.1
                            ? Math.random() < 0.5 ? '!' : '?'
                            : '.';
                this.lastSentenceHadComma = false;
            }
        }

        sentence = sentence.charAt(0).toUpperCase() + sentence.substring(1);

        return sentence;
    };

    GaemzIpsum.prototype.createParagraph = function(num, indieRatio,
                                                    minSentInParLength, maxSentInParLength,
                                                    minSentLength, maxSentLength, initQuote) {
        num = num || 2;
        indieRatio = indieRatio || 0;
        minSentInParLength = minSentInParLength || 2;
        maxSentInParLength = maxSentInParLength || 6;
        minSentLength = minSentLength || 5;
        maxSentLength = maxSentLength || 15;

        this.lastSentenceHadQuote = initQuote || false;;

        var ipsumText = [],
            sentencesPerParagraph,
            paragraphSentences,
            sentenceLength;

        while(num--) {
            sentencesPerParagraph = getRandomInt(minSentInParLength, maxSentInParLength);
            paragraphSentences = [];

            while(sentencesPerParagraph--) {
                var comma = (sentencesPerParagraph > 0);
                sentenceLength = getRandomInt(minSentLength, maxSentLength);
                paragraphSentences.push(this.createSentence(sentenceLength, indieRatio, comma));
            }

            ipsumText.push(paragraphSentences.join(' '));
            this.lastSentenceHadQuote = false;
        }

        return ipsumText;
    };

    function getRandomInt(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

  window.GaemzIpsum = GaemzIpsum;
})();
